version: '3.1'

services:
  app:
    image: 'app:latest'
    ports:
      - "8081:8081"
    build:
      context: src/main/docker
      dockerfile: Dockerfile
    container_name: app

    environment:
      - JWT_SECRET=${JWT_SECRET}